[package]
name = "tangleproof"
version = "0.1.0"
authors = ["Thoralf-M <thoralf.mue@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iota-core = {git = "https://github.com/iotaledger/iota.rs", branch = "dev", default-features = false}
# iota-core = {git = "https://github.com/Thoralf-M/iota.rs", branch = "dev"}
# iota-core = {path = "../iota.rs/iota-core/"}
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
# For main.rs
tokio = { version = "0.2", features = ["full"] }
dotenv_codegen = "0.15.0"